In [2]:
import pandas as pd
pd.__version__

'1.0.5'

In [4]:
df_left = pd.DataFrame(
      {'X':['x0','x1','x2','x3'], 
       'W':['w0','w1','w2','w3'], 
       'Y':['y0','y1','y2','y3'], 
       'Mix':['y2','y3','a2','a3']}, 
       index =[0,1,2,3])
df_left

    X   W   Y Mix
0  x0  w0  y0  y2
1  x1  w1  y1  y3
2  x2  w2  y2  a2
3  x3  w3  y3  a3

In [5]:
df_right = pd.DataFrame(
    {'Z':['z2','z3','z4','z5'],
     'A':['a2','a3','a4','a5'],
     'Y':['y2','y3','y4','y5']},
    index = [2,3,4,5])
df_right

    Z   A   Y
2  z2  a2  y2
3  z3  a3  y3
4  z4  a4  y4
5  z5  a5  y5

In [6]:
pd.merge(df_left,df_right)

    X   W   Y Mix   Z   A
0  x2  w2  y2  a2  z2  a2
1  x3  w3  y3  a3  z3  a3

In [11]:
# Especificando el tipo de union
pd.merge(df_left,df_right, how='inner', on='Y')

    X   W   Y Mix   Z   A
0  x2  w2  y2  a2  z2  a2
1  x3  w3  y3  a3  z3  a3

In [12]:
pd.merge(df_left,df_right, how='inner', left_on='Mix', right_on='Y')

    X   W Y_x Mix   Z   A Y_y
0  x0  w0  y0  y2  z2  a2  y2
1  x1  w1  y1  y3  z3  a3  y3

In [13]:
pd.merge(df_left,df_right, how='inner', left_on='Mix', right_on='A')

    X   W Y_x Mix   Z   A Y_y
0  x2  w2  y2  a2  z2  a2  y2
1  x3  w3  y3  a3  z3  a3  y3

Cuantos tipos de merge podemos tener?
![](http://www.datasciencemadesimple.com/wp-content/uploads/2017/09/join-or-merge-in-python-pandas-1.png)

Ejemplos

In [16]:
df_left = pd.DataFrame(
      {'X':['x0','x1','x2','x3'], 
       'W':['w0','w1','w2','w3'], 
       'Y':['y0','y1','y2','y3']}, 
       index =[0,1,2,3])
df_left

    X   W   Y
0  x0  w0  y0
1  x1  w1  y1
2  x2  w2  y2
3  x3  w3  y3

In [17]:
df_right = pd.DataFrame(
    {'Z':['z2','z3','z4','z5'],
     'A':['a2','a3','a4','a5'],
     'Y':['y2','y3','y4','y5']},
    index = [2,3,4,5])
df_right

    Z   A   Y
2  z2  a2  y2
3  z3  a3  y3
4  z4  a4  y4
5  z5  a5  y5

In [18]:
pd.merge(df_left, df_right, how='inner', on='Y')

    X   W   Y   Z   A
0  x2  w2  y2  z2  a2
1  x3  w3  y3  z3  a3

In [19]:
 pd.merge(df_left, df_right, how='left', on='Y')

    X   W   Y    Z    A
0  x0  w0  y0  NaN  NaN
1  x1  w1  y1  NaN  NaN
2  x2  w2  y2   z2   a2
3  x3  w3  y3   z3   a3

In [20]:
 pd.merge(df_left, df_right, how='right', on='Y')

     X    W   Y   Z   A
0   x2   w2  y2  z2  a2
1   x3   w3  y3  z3  a3
2  NaN  NaN  y4  z4  a4
3  NaN  NaN  y5  z5  a5

In [21]:
 pd.merge(df_left, df_right, how='outer', on='Y')

     X    W   Y    Z    A
0   x0   w0  y0  NaN  NaN
1   x1   w1  y1  NaN  NaN
2   x2   w2  y2   z2   a2
3   x3   w3  y3   z3   a3
4  NaN  NaN  y4   z4   a4
5  NaN  NaN  y5   z5   a5

In [22]:
# Agrego segunda columna A para explorar otros merge
df_left = pd.DataFrame(
      {'X':['x0','x1','x2','x3'], 
       'W':['w0','w1','w2','w3'], 
       'Y':['y0','y1','y2','y3'],
       'A':['a0','a1','a2','a3']
       }, 
       index =[0,1,2,3])
df_left

    X   W   Y   A
0  x0  w0  y0  a0
1  x1  w1  y1  a1
2  x2  w2  y2  a2
3  x3  w3  y3  a3

In [23]:
 pd.merge(df_left, df_right, how='outer', on=['Y', 'A'])

     X    W   Y   A    Z
0   x0   w0  y0  a0  NaN
1   x1   w1  y1  a1  NaN
2   x2   w2  y2  a2   z2
3   x3   w3  y3  a3   z3
4  NaN  NaN  y4  a4   z4
5  NaN  NaN  y5  a5   z5

In [24]:
 # Cambiando los subfijos
 pd.merge(df_left, df_right, how='outer', on='A', suffixes=['_left', '_right'])

     X    W Y_left   A    Z Y_right
0   x0   w0     y0  a0  NaN     NaN
1   x1   w1     y1  a1  NaN     NaN
2   x2   w2     y2  a2   z2      y2
3   x3   w3     y3  a3   z3      y3
4  NaN  NaN    NaN  a4   z4      y4
5  NaN  NaN    NaN  a5   z5      y5